### ISSUE TITLE
Lack of support for capital letters in name

### ISSUE THREAD

**Issue by TriXXeD** [MyrionSC/foundafunny#2]
![image](https://user-images.githubusercontent.com/6638014/39350526-b57f4544-49fe-11e8-8aca-9a133f5dc8dd.png)

**Comment by MyrionSC** [comment]
Der burde bare køres en toLower på det. Forvirer det ikke mere end det gavner hvis man kan lave uppercase letters?

**Comment by MyrionSC** [comment]
fuck it, vi giver bare lov til at have store bogstaver, lad os se hvordan det går
